### ISSUE TITLE
Is physic simulation still accurate after timeScale at 100 ?

### ISSUE THREAD

**Issue by SPINACHCEO** [Unity-Technologies/ml-agents#70]
Hi,
I am kind of confused here.
I tried to train the tennis example at time scale 100, and succeed.
So since tennis is using physic collision I should know physic will still works fun even if timeScale is 100.

Then I made my own environment which is a little tank game with collision based hit detection.
(Whenever a bullet collide with a tank, decrease it's health.)

But when I go with timeScale 100, seems like all my bullet collision is ignored.
Has anyone faced the same problem or is only me did something totally wrong ?

In addition, I did not use OnCollisionEnter to listen to collision. Instead I am using Physics.OverlapSphere in Update. Could this be the problem ?

And I am wondering if FixedUpdate will be called 100(timeScale) * 50(default step) / 60(fps) times every frame ?
If it is, maybe I should put Physics.OverlapSphere in FixedUpdate and physic will be still accurate.

Thanks for your time :)

**Comment by vincentpierre** [comment]
`FixedUpdate` is called every Physics update while update is run every frame update. Some details are given [here](https://stackoverflow.com/questions/34447682/what-is-the-difference-between-update-fixedupdate-in-unity). If you increase the `timeScale` the number of updates per second will not change while the fixed update per second will. Try putting Physics.OverlapSphere in FixedUpdate like you suggested, it should fix the problem. Please tell us if it does not. Thank you for pointing this out.

**Comment by SPINACHCEO** [comment]
@vincentpierre Thanks for the reply.

I will try to use FixedUpdate later and see if it works. 

Since the environment I am talking about is really a simple game, I changed all  Physics.OverlapSphere to OnCollisionEnter. Collision works good now, but the training still not working. Can't make my agents become smarter after an hour of training. Tried to adjust reward function but still no improvement. :(

**Comment by artoul** [comment]
your states need to be around 1 ... so for example if you are sending a state that is the position x of a game object  that can reach lets 1000 then devide the number by 1000 ... so all your position will be from -1 to 1... i am sure this is your problem

**Comment by SPINACHCEO** [comment]
@artoul Thanks for the reply. I had scaled all state between -1 and 1.

Maybe this is because I don't really know the concept of "invert reward function" works.
I have two agent using a same brain and trying to beat the other. 
In this case, how should I reward them ?

**Comment by awjuliani** [comment]
Hi @SPINACHCEO,

This depends on the kind of behavior you would like them to learn. Can you explain the task and current reward function a little bit?

**Comment by SPINACHCEO** [comment]
@awjuliani Hi, thanks for the reply.
My task is a simple "soccer" like game. It looks like this.
![screen shot 2017-10-12 at 12 48 03 am](https://user-images.githubusercontent.com/8978490/31454159-0fcbe510-aee7-11e7-9d69-8b7e81205737.png)

I use some relatively value as state:
`		var v = m_rigidbody.velocity / maxMoveSpeed;
		var av = m_rigidbody.angularVelocity / maxRotateSpeed;
		var db = ball.position - transform.position;
		var dg = goal.position - transform.position;
		
		state.Add(v.x);
		state.Add(v.z * invert);
		state.Add(av.y * invert);
		state.Add(transform.forward.x * invert);
		state.Add(transform.forward.z * invert);
		state.Add(db.x/10f * invert);
		state.Add(db.z/25f * invert);
		state.Add(dg.x/10f * invert);
		state.Add(dg.z/25f * invert);`
Where `invert` is either 1 or -1 for each agent. And each agent have 4 action, move and rotate in both direction.

Reward function is :
1. When a agent hit the ball, reward +0.1f
2. When ball goal, the goal agent reward + 0.2f, the other -0.2f.

When I train this, the reward just randomly go up and down and agent still acts like a fool after many step of train.

Please help me point out what I did is wrong.
Thanks for your time.

**Comment by awjuliani** [comment]
Hi @SPINACHCEO,

Looking at your reward function, I am unsure what can prevent the agent from simply bumping into the ball many times in a row without attempting to make progress? You might want to scale it down, or only provide a reward the first time the ball is hit by an agent.
